name: Run Makefile

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"

      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

      - name: Compile pointercrate
        run: make package

      - name: Compile pointercrate
        run: make package TIPA=1

      - name: Upload app to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pointercrate
          path: ${{ github.workspace }}/packages/*
